spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bkool
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      port: 7380
  cache:
    redis:
      time-to-live: 600000
